#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libstaroffice
Version  : 0.0.7
Release  : 3
URL      : https://dev-www.libreoffice.org/src/libstaroffice-0.0.7.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libstaroffice-0.0.7.tar.xz
Summary  : A library for reading StarOffice documents
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: libstaroffice-bin = %{version}-%{release}
Requires: libstaroffice-lib = %{version}-%{release}
Requires: libstaroffice-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(zlib)

%description
The purpose of libstaroffice is to build a filter for old StarOffice's
documents(.sdc, .sdw, ...) based on librevenge(see
https://sourceforge.net/p/libwpd/wiki/librevenge/ and
http://www.documentliberation.org/projects/ ).

%package bin
Summary: bin components for the libstaroffice package.
Group: Binaries
Requires: libstaroffice-license = %{version}-%{release}

%description bin
bin components for the libstaroffice package.


%package dev
Summary: dev components for the libstaroffice package.
Group: Development
Requires: libstaroffice-lib = %{version}-%{release}
Requires: libstaroffice-bin = %{version}-%{release}
Provides: libstaroffice-devel = %{version}-%{release}
Requires: libstaroffice = %{version}-%{release}

%description dev
dev components for the libstaroffice package.


%package doc
Summary: doc components for the libstaroffice package.
Group: Documentation

%description doc
doc components for the libstaroffice package.


%package lib
Summary: lib components for the libstaroffice package.
Group: Libraries
Requires: libstaroffice-license = %{version}-%{release}

%description lib
lib components for the libstaroffice package.


%package license
Summary: license components for the libstaroffice package.
Group: Default

%description license
license components for the libstaroffice package.


%prep
%setup -q -n libstaroffice-0.0.7
cd %{_builddir}/libstaroffice-0.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587592751
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1587592751
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libstaroffice
cp %{_builddir}/libstaroffice-0.0.7/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libstaroffice/3704f4680301a60004b20f94e0b5b8c7ff1484a9
cp %{_builddir}/libstaroffice-0.0.7/COPYING.MPL %{buildroot}/usr/share/package-licenses/libstaroffice/9744cedce099f727b327cd9913a1fdc58a7f5599
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sd2raw
/usr/bin/sd2svg
/usr/bin/sd2text
/usr/bin/sdc2csv
/usr/bin/sdw2html

%files dev
%defattr(-,root,root,-)
/usr/include/libstaroffice-0.0/libstaroffice/STOFFDocument.hxx
/usr/include/libstaroffice-0.0/libstaroffice/libstaroffice.hxx
/usr/lib64/libstaroffice-0.0.so
/usr/lib64/pkgconfig/libstaroffice-0.0.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libstaroffice/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libstaroffice-0.0.so.0
/usr/lib64/libstaroffice-0.0.so.0.0.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libstaroffice/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/libstaroffice/9744cedce099f727b327cd9913a1fdc58a7f5599
